#!/usr/bin/env bash
#
# Submit a spatialized multiwell Allen-Cahn pilot using the existing PDE queue.
#
# This launcher intentionally has no SBATCH header: it submits the repository's
# established queue script with Allen-Cahn-specific environment defaults.

set -euo pipefail

EXPERIMENT_TAG="${EXPERIMENT_TAG:-allen_cahn_multistable_pde_pilot_20260628}"
SYSTEMS_CSV="${SYSTEMS_CSV:-allen_cahn_4}"
MODEL_VARIANTS_CSV="${MODEL_VARIANTS_CSV:-conv_lista,conv_dense,conv_sparse_mlp}"
SEEDS_CSV="${SEEDS_CSV:-0,1,2}"
GRID_SIZE="${GRID_SIZE:-16}"
DIFFUSION="${DIFFUSION:-0.001}"
RK4_DT="${RK4_DT:-0.005}"
SUBSTEPS_PER_OBSERVATION="${SUBSTEPS_PER_OBSERVATION:-4}"
TRAJECTORY_LENGTH="${TRAJECTORY_LENGTH:-24}"
LABEL_EXTRA_OBSERVATIONS="${LABEL_EXTRA_OBSERVATIONS:-24}"
TRAIN_TRAJECTORIES="${TRAIN_TRAJECTORIES:-48}"
VAL_TRAJECTORIES="${VAL_TRAJECTORIES:-12}"
TEST_TRAJECTORIES="${TEST_TRAJECTORIES:-12}"
MIN_LATENT_STATE_RATIO="${MIN_LATENT_STATE_RATIO:-4.0}"
HIDDEN_CHANNELS="${HIDDEN_CHANNELS:-32}"
NUM_BLOCKS="${NUM_BLOCKS:-2}"
CONV_ACTIVATION="${CONV_ACTIVATION:-tanh}"
NUM_STEPS="${NUM_STEPS:-3000}"
BATCH_SIZE="${BATCH_SIZE:-8}"
SEQUENCE_LENGTH="${SEQUENCE_LENGTH:-8}"
LISTA_ALPHA="${LISTA_ALPHA:-1e-3}"
SUPPORT_THRESHOLD="${SUPPORT_THRESHOLD:-1e-4}"
FAMILY_JACCARD="${FAMILY_JACCARD:-0.5}"
EVAL_HORIZONS="${EVAL_HORIZONS:-1,4,8,12,20}"
EVAL_HORIZON="${EVAL_HORIZON:-12}"
PREFLIGHT_VALIDATE_DATASETS="${PREFLIGHT_VALIDATE_DATASETS:-1}"
PREFLIGHT_MIN_LABELS_PER_SPLIT="${PREFLIGHT_MIN_LABELS_PER_SPLIT:-2}"
ARRAY_THROTTLE="${ARRAY_THROTTLE:-3}"
RUNNER_PARTITION="${RUNNER_PARTITION:-long}"
RUNNER_GRES="${RUNNER_GRES:-gpu:1}"
RUNNER_TIME="${RUNNER_TIME:-04:00:00}"
RUNNER_MEM="${RUNNER_MEM:-24G}"
RUNNER_CPUS="${RUNNER_CPUS:-4}"
K_STABILITY_WEIGHT="${K_STABILITY_WEIGHT:-0}"

export EXPERIMENT_TAG SYSTEMS_CSV MODEL_VARIANTS_CSV SEEDS_CSV GRID_SIZE
export DIFFUSION RK4_DT SUBSTEPS_PER_OBSERVATION TRAJECTORY_LENGTH LABEL_EXTRA_OBSERVATIONS
export TRAIN_TRAJECTORIES VAL_TRAJECTORIES TEST_TRAJECTORIES MIN_LATENT_STATE_RATIO
export HIDDEN_CHANNELS NUM_BLOCKS NUM_STEPS BATCH_SIZE SEQUENCE_LENGTH LISTA_ALPHA
export CONV_ACTIVATION
export SUPPORT_THRESHOLD FAMILY_JACCARD EVAL_HORIZONS EVAL_HORIZON ARRAY_THROTTLE
export RUNNER_PARTITION RUNNER_GRES RUNNER_TIME RUNNER_MEM RUNNER_CPUS
export PREFLIGHT_VALIDATE_DATASETS PREFLIGHT_MIN_LABELS_PER_SPLIT K_STABILITY_WEIGHT

sbatch scripts/queue_spatialized_reaction_diffusion_benchmark.sh
