#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(git -C "${SLURM_SUBMIT_DIR:-$PWD}" rev-parse --show-toplevel)"
cd "${ROOT_DIR}"
source scripts/common/cluster_env.sh
REPO_ROOT="${ROOT_DIR}"
OUTPUT_ROOT="${OUTPUT_ROOT:-${SKAE_SCRATCH_ROOT}/allen_cahn_mechanistic_bridge_20260720_v2}"
CARD=${REPO_ROOT}/experiments/neurips_2026/allen_cahn_mechanistic_bridge/prediction_card.json
MANIFEST=${REPO_ROOT}/experiments/neurips_2026/allen_cahn_mechanistic_bridge/source_manifest.sha256
MECHANISM_DECISION="${MECHANISM_DECISION:-${SKAE_SCRATCH_ROOT}/allen_cahn_support_subspaces_20260720_v4/summary/decision.json}"
PROFILE_DECISION="${PROFILE_DECISION:-${SKAE_SCRATCH_ROOT}/allen_cahn_support_subspaces_20260720_v4/profile/decision.json}"
DATASET_MANIFEST=${OUTPUT_ROOT}/dataset_manifest.json
EXPECTED_CARD_SHA256=caa247afdffa666591d6694d6e51286b02b3d80d4083b6e6d71af2bdb9a4fb4b
EXPECTED_SOURCE_MANIFEST_SHA256=8585c4184e6d4a2e5738b47dd9cd2a3a5f0e4b0045b74a72598758af926098d8
EXPECTED_MECHANISM_DECISION_SHA256=__FREEZE_AFTER_MECHANISM__
EXPECTED_PROFILE_DECISION_SHA256=043ee246bdfcc8d4ef50431d234274404bfd2438114c8755d513a62f5a04b993
EXPECTED_DATASET_MANIFEST_SHA256=__FREEZE_AFTER_GENERATION__
BATCH_SIZE=128
test "$(sha256sum "${CARD}" | awk '{print $1}')" = "${EXPECTED_CARD_SHA256}"
test "$(sha256sum "${MANIFEST}" | awk '{print $1}')" = "${EXPECTED_SOURCE_MANIFEST_SHA256}"
test "$(sha256sum "${MECHANISM_DECISION}" | awk '{print $1}')" = "${EXPECTED_MECHANISM_DECISION_SHA256}"
test "$(sha256sum "${PROFILE_DECISION}" | awk '{print $1}')" = "${EXPECTED_PROFILE_DECISION_SHA256}"
test "$(sha256sum "${DATASET_MANIFEST}" | awk '{print $1}')" = "${EXPECTED_DATASET_MANIFEST_SHA256}"
test ! -e "${OUTPUT_ROOT}/field_artifacts"
EXTRACT_JOB=$(sbatch --parsable --export=ALL,OUTPUT_ROOT="${OUTPUT_ROOT}",MECHANISM_DECISION="${MECHANISM_DECISION}",PROFILE_DECISION="${PROFILE_DECISION}",DATASET_MANIFEST="${DATASET_MANIFEST}",EXPECTED_CARD_SHA256="${EXPECTED_CARD_SHA256}",EXPECTED_SOURCE_MANIFEST_SHA256="${EXPECTED_SOURCE_MANIFEST_SHA256}",EXPECTED_MECHANISM_DECISION_SHA256="${EXPECTED_MECHANISM_DECISION_SHA256}",EXPECTED_PROFILE_DECISION_SHA256="${EXPECTED_PROFILE_DECISION_SHA256}",EXPECTED_DATASET_MANIFEST_SHA256="${EXPECTED_DATASET_MANIFEST_SHA256}",BATCH_SIZE="${BATCH_SIZE}" "${REPO_ROOT}/scripts/neurips_2026/allen_cahn_mechanistic_bridge/run_extract.sh")
sbatch --parsable --dependency=afterok:"${EXTRACT_JOB}" --export=ALL,OUTPUT_ROOT="${OUTPUT_ROOT}",MECHANISM_DECISION="${MECHANISM_DECISION}",EXPECTED_CARD_SHA256="${EXPECTED_CARD_SHA256}",EXPECTED_SOURCE_MANIFEST_SHA256="${EXPECTED_SOURCE_MANIFEST_SHA256}",EXPECTED_MECHANISM_DECISION_SHA256="${EXPECTED_MECHANISM_DECISION_SHA256}",EXPECTED_PROFILE_DECISION_SHA256="${EXPECTED_PROFILE_DECISION_SHA256}",EXPECTED_DATASET_MANIFEST_SHA256="${EXPECTED_DATASET_MANIFEST_SHA256}" "${REPO_ROOT}/scripts/neurips_2026/allen_cahn_mechanistic_bridge/run_field_manifest.sh"
